stages:
  - backend
  - frontend

backendtest:
  stage: backend
  script:
    - cd backend
    - pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
    - python3 -m coverage run --source="." manage.py test --noinput
    - python3 -m coverage report
  tags:
    - txy2

backendlint:
  stage: backend
  script:
    - cd backend
    - pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
    - pylint --rcfile=.pylintrc ./**/*.py || exit $((35 & $?))
  allow_failure: false
  tags:
    - txy3

frontendtest:
  stage: frontend
  script:
    - cd frontend
    - npm install --registry https://registry.npm.taobao.org
    - npm run test
  allow_failure: false
  tags:
    - txy2

frontendlint:
  stage: frontend
  script:
    - cd frontend
    - npm install --registry https://registry.npm.taobao.org
    - npm run eslint
    - npm run stylelint
  allow_failure: false
  tags:
    - txy3
